### ISSUE TITLE
Parse exception converting JSON to object

### ISSUE THREAD

**Issue by Kalvin126** [jenkinsci/violation-comments-to-github-plugin#14]
Trying to get it to post comments to our Enterprise GitHub instance, I am getting this error. Does this support enterprise GitHub?

```
java.lang.RuntimeException: java.io.IOException: Parse exception converting JSON to object
	at se.bjurr.violations.comments.github.lib.GitHubCommentsProvider.<init>(GitHubCommentsProvider.java:59)
	at 
```

**Comment by tomasbjerre** [comment]
What else do you see in the stacktrace?
I found this bug, that might be it:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=400793

**Comment by sfontana** [comment]
I'm also getting this error

```
java.lang.RuntimeException: java.io.IOException: Parse exception converting JSON to object
	at se.bjurr.violations.comments.github.lib.GitHubCommentsProvider.<init>(GitHubCommentsProvider.java:59)
	at se.bjurr.violations.comments.github.lib.ViolationCommentsToGitHubApi.toPullRequest(ViolationCommentsToGitHubApi.java:136)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer.doPerform(JvctgPerformer.java:137)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer$1.invoke(JvctgPerformer.java:230)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer$1.invoke(JvctgPerformer.java:218)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2873)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Parse exception converting JSON to object
	at org.eclipse.egit.github.core.client.GitHubClient.parseJson(GitHubClient.java:424)
	at org.eclipse.egit.github.core.client.GitHubClient.parseJson(GitHubClient.java:403)
	at org.eclipse.egit.github.core.client.GitHubClient.parseError(GitHubClient.java:514)
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:547)
	at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:740)
	at org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:173)
	at org.eclipse.egit.github.core.service.GitHubService.getAll(GitHubService.java:151)
	at org.eclipse.egit.github.core.service.GitHubService.getAll(GitHubService.java:135)
	at org.eclipse.egit.github.core.service.PullRequestService.getCommits(PullRequestService.java:319)
	at se.bjurr.violations.comments.github.lib.GitHubCommentsProvider.<init>(GitHubCommentsProvider.java:56)
	... 13 more
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 10
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.Gson.fromJson(Gson.java:795)
	at com.google.gson.Gson.fromJson(Gson.java:761)
	at org.eclipse.egit.github.core.client.GitHubClient.parseJson(GitHubClient.java:422)
	... 22 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 10
	at com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:165)
	... 25 more
```


Not sure how to solve it :(

**Comment by tomasbjerre** [comment]
This is a terrible error coming from Eclipse GitHub Client... all it says is that som URL was invoked and JSON was not returned.

I would double check that `gitHubUrl` is correctly defined.

It can be a firewall, or proxy, between Jenkins and GitHub that intercepts the request and response with none JSON.

If possible, try invoke a `curl` command on the Jenkins server on GitHub to make sure the API can be reached and responds with JSON.

**Comment by sfontana** [comment]
Agree, it's a horrible error message.
I tried `curl https://api.github.com/` from my Jenkins server and JSON is returned correctly.
Will keep digging :)

**Comment by sfontana** [comment]
Couldn't find anything unfortunately.
I also tried with a public repo (I thought it was worth trying to exclude access rights related issues) and there I have the same problem:

```
gitHubUrl: https://api.github.com
repositoryOwner:  sfontana
repositoryName: django
pullRequestId: 1
credentialsId: true
oAuth2Token: false
createSingleFileComments: true
createCommentWithAllSingleFileComments: true
commentOnlyChangedContent: true
minSeverity: INFO
keepOldComments: true
test1 with pattern .*\.py$ 
test2 with pattern .*\.py$ 
Using username / password
Running Jenkins Violation Comments To GitHub
PR 1
Workspace: /var/lib/jenkins/workspace/test_dj
Found 0 violations from ViolationConfig [pattern=.*\.py$ , reporter=test1, parser=PYLINT].
Found 0 violations from ViolationConfig [pattern=.*\.py$ , reporter=test2, parser=PYDOCSTYLE].
PR:  sfontana/django/1 on https://api.github.com
java.lang.RuntimeException: java.io.IOException: Parse exception converting JSON to object
	at se.bjurr.violations.comments.github.lib.GitHubCommentsProvider.<init>(GitHubCommentsProvider.java:59)
	at se.bjurr.violations.comments.github.lib.ViolationCommentsToGitHubApi.toPullRequest(ViolationCommentsToGitHubApi.java:136)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer.doPerform(JvctgPerformer.java:137)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer$1.invoke(JvctgPerformer.java:230)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer$1.invoke(JvctgPerformer.java:218)
.....
```


What's interesting is that no violations are found even though I'm pretty sure there should be some at least.

Any ideas on how I can find more details to give you?


Ps: I also tried to change `https://api.github.com` to a website that I own intending to intercept the request that is made, but I never get any requests so it seems the problem occurs before the request is made.

**Comment by tomasbjerre** [comment]
`pattern` should be name of the report-files. The output of Pylint and Pydocstyle needs to be in a file and those file names should match this pattern.

If the request is not being intercepted by the website you own I think that there is a proxy that blocks the request and responds with something that is not JSON...

**Comment by Kalvin126** [comment]
Solved this issue a while back. I believe the fix was incorrect credentials since my company requires ssh instead of user + password
