### ISSUE TITLE
Found 0 violations from ViolationConfig

### ISSUE THREAD

**Issue by Jasonparrish** [jenkinsci/violation-comments-to-github-plugin#7]
Hello all!

I am trying to configure my Jenkins server to scan my project using the pep8 utility in Ubuntu by using the following command in my Jenkins build script (Execute Shell):

`pep8 testing/ > pep8.out`

Next, I use the violations plugin and enter “pep8.out” under the XML filename pattern. This works perfectly for coming up with results for my entire project…

However, I want to scan only the changes in a pull request for styl violations, so I am using the Violation Comments to GitHub Plugin for this task.

As I am using the github pull request builder plugin, I have entered this as my Pull Request ID: 

`${ghprbPullId}`

Next, I check the “Comment only changed part of files” box and put in “pep8.out” as my pattern next to the “FLAKE8” option. From what I understand, PEP8 and FLAKE8 should be cross compatible.

There are plenty of violations that should be detected out of the box (for instance, I’m using 2 spaces instead of 4 for python3). This should be getting flagged on my sample pull request. But I am seeing the following output in my console:

```
 ---
--- Jenkins Violation Comments to GitHub ---
---
pullRequestId: 83
usernamePasswordCredentialsId: false
username: false
password: false
createSingleFileComments: false
createCommentWithAllSingleFileComments: true
commentOnlyChangedContent: true
CHECKSTYLE with pattern 
CSSLINT with pattern 
LINT with pattern pylint.out
FINDBUGS with pattern 
JSHINT with pattern 
PMD with pattern 
CPPCHECK with pattern 
RESHARPER with pattern 
FLAKE8 with pattern ./pep8.out
CPPLINT with pattern 
XMLLINT with pattern 
PERLCRITIC with pattern 
PITEST with pattern 
ANDROIDLINT with pattern 
Running Jenkins Violation Comments To GitHub
Will comment 83
Workspace: /var/lib/jenkins/workspace/Project Style Checks
Found 0 violations from ViolationConfig [pattern=./pep8.out, reporter=FLAKE8].
```

(I’ve removed any potential private text, but this should give a decent idea of what I’m seeing)

When I went digging into the logs, I found this error as well. TBH not sure if it is related or not:

```
java.lang.NullPointerException: GitHubUrl
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204)
	at se.bjurr.violations.comments.github.lib.ViolationCommentsToGitHubApi.checkState(ViolationCommentsToGitHubApi.java:170)
	at se.bjurr.violations.comments.github.lib.ViolationCommentsToGitHubApi.toPullRequest(ViolationCommentsToGitHubApi.java:155)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer.doPerform(JvctgPerformer.java:103)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer$1.invoke(JvctgPerformer.java:138)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer$1.invoke(JvctgPerformer.java:125)
	at hudson.FilePath.act(FilePath.java:1018)
	at hudson.FilePath.act(FilePath.java:996)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer.jvctsPerform(JvctgPerformer.java:125)
	at org.jenkinsci.plugins.jvctg.ViolationsToGitHubRecorder.perform(ViolationsToGitHubRecorder.java:60)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

```

**Comment by tomasbjerre** [comment]
Perhaps your pattern should be `.*/pep8\\.out\$`. Its different from the violations plugin. This plugin is using regexp as pattern.

Also are you really sure you specified a Github URL?

The expected format of the pep8.out is like this: https://github.com/tomasbjerre/violations-lib/tree/master/src/test/resources/flake8
