### ISSUE TITLE
Malformed URL Exception if gitHubUrl not included in config

### ISSUE THREAD

**Issue by maxpowa** [jenkinsci/violation-comments-to-github-plugin#9]
Only thing I could think of that's out of the ordinary here, some special characters do exist in the password that may need to be escaped.

```stacktrace
java.lang.IllegalArgumentException: java.net.MalformedURLException: no protocol: 
	at org.eclipse.egit.github.core.client.GitHubClient.createClient(GitHubClient.java:73)
	at se.bjurr.violations.comments.github.lib.GitHubCommentsProvider.<init>(GitHubCommentsProvider.java:41)
	at se.bjurr.violations.comments.github.lib.ViolationCommentsToGitHubApi.toPullRequest(ViolationCommentsToGitHubApi.java:126)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer.doPerform(JvctgPerformer.java:107)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer$1.invoke(JvctgPerformer.java:180)
	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer$1.invoke(JvctgPerformer.java:167)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2731)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.MalformedURLException: no protocol: 
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.eclipse.egit.github.core.client.GitHubClient.createClient(GitHubClient.java:68)
	... 15 more
```

**Comment by tomasbjerre** [comment]
The URL is printed in the log, here:
https://github.com/jenkinsci/violation-comments-to-github-plugin/blob/master/src/main/java/org/jenkinsci/plugins/jvctg/perform/JvctgPerformer.java#L92

And that exact value is passed to EGit:
https://github.com/tomasbjerre/violation-comments-to-github-lib/blob/master/src/main/java/se/bjurr/violations/comments/github/lib/GitHubCommentsProvider.java#L41

And the crash happens in EGit. So I would say its an EGit bug, or your URL is not valid.

**Comment by maxpowa** [comment]
So adding `gitHubUrl: 'https://api.github.com/',` to the config list worked, why doesn't it fall back to that as default?

**Comment by tomasbjerre** [comment]
I'm releaseing this now in 1.38. Will be in the update sites within a few hours. Open issue again if any problems!
